# Generated by Django 4.1.6 on 2023-04-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('txt_app', '0002_delete_checkboxdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_options', models.IntegerField(default=0)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
    ]
